<?php

require_once (__DIR__ . '/../../../adm_program/system/common.php');

require_once (__DIR__ . '/engine/bootstrap.php');

if ( $GLOBALS['gPreferences']['registration_mode'] == 0) {
	$GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_MODULE_DISABLED'));
	// => EXIT
}
# org
$organisation_id = $GLOBALS['gCurrentOrganization']->getValue('org_id');

/**
 * handle the form POST
 */
function handle_form_post ( $organisation_id ) {

	# create a registration
	$getNewUser = 2;

    # splice in fields we need
	$email_field_post_index = $email_param = 'usf-'. $GLOBALS['gProfileFields']->mProfileFields['EMAIL']->getValue('usf_id');

    $autogenerated_password = \cantabnyc\auto_generate_password();

    $email = $_POST[$email_field_post_index];

	$_POST['usr_login_name']   = $_POST[$email_field_post_index];
	$_POST['usr_password']     = $autogenerated_password;
    $_POST['password_confirm'] = $_POST['usr_password'];
    $_POST['activation_code'] = \cantabnyc\generateActivationCode();

    # process
	$user = new UserRegistration( $GLOBALS['gDb'],  $GLOBALS['gProfileFields'], 0);
	$user->setOrganization( $organisation_id );

	# set the username/password for saving
	$user->setValue('usr_login_name', $_POST['usr_login_name']);
    $user->setPassword($_POST['usr_password']);
    $user->setValue('usr_activation_code', $_POST['activation_code']);

	# ensure fields set
	if ($_POST['usr_login_name'] === '') {
		$GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_FIELD_EMPTY', $GLOBALS['gL10n']->get('SYS_USERNAME')));
		// => EXIT
	}

	if ($_POST['usr_password'] === '') {
		$GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_FIELD_EMPTY', $GLOBALS['gL10n']->get('SYS_PASSWORD')));
		// => EXIT
	}

	// Passwort muss mindestens 8 Zeichen lang sein
	if (strlen($_POST['usr_password']) < PASSWORD_MIN_LENGTH) {
		$GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('PRO_PASSWORD_LENGTH'));
		// => EXIT
	}

	// beide Passwortfelder muessen identisch sein
	if ($_POST['usr_password'] !== $_POST['password_confirm']) {
		$GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('PRO_PASSWORDS_NOT_EQUAL'));
		// => EXIT
	}

	if (PasswordHashing::passwordStrength($_POST['usr_password'], $user->getPasswordUserData()) < $GLOBALS['gPreferences']['password_min_strength']) {
		$GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('PRO_PASSWORD_NOT_STRONG_ENOUGH'));
		// => EXIT
	}
	// nun alle Profilfelder pruefen
	foreach($GLOBALS['gProfileFields']->mProfileFields as $field) {
            $fieldKey = $field->getValue('usf_name_intern');
			$post_id = 'usf-'. $field->getValue('usf_id');
			// check and save only fields that aren't disabled
			if ($field->getValue('usf_disabled') == 0
			|| ($field->getValue('usf_disabled') == 1 && $GLOBALS['gCurrentUser']->hasRightEditProfile($user, false))
			|| ($field->getValue('usf_disabled') == 1 && $getNewUser > 0))
			{
					if(isset($_POST[$post_id]))
					{
                        // Pflichtfelder muessen gefuellt sein
                        // E-Mail bei Registrierung immer !!!
                        if(
                            ($fieldKey === 'EMAIL')
                        ){
                            // # validate email is in format: Starts here
                            if(!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                                $GLOBALS['gMessage']->show('ERR1: Invalid value for '.$fieldKey);
                                throw new \Exception('ERR1: Invalid value for '.$fieldKey);
                            }
                            // # validate email is in format: Ends here

                            // # Check if already exists the email: Starts here
                            $usf_id = $field->getValue('usf_id');
                            $sqlForUniqueEmail = "SELECT usd_value
                                                    FROM adm_user_data
                                                    WHERE
                                                    TRIM(LOWER(usd_value)) = TRIM(LOWER('$email'))
                                                    AND usd_usf_id = $usf_id";
                            $uniqueEmailQuery = $GLOBALS['gDb']->query($sqlForUniqueEmail);
                            $result = $uniqueEmailQuery->fetch();
                            if($result && count($result)){
                                $GLOBALS['gMessage']->show('ERR2: Duplicate field value for '.$fieldKey);
                                throw new \Exception('ERR2: Duplicate field value for '.$fieldKey);
                            }
                            // # Check if already exists the email: Ends here
                        }
                        if((strlen($_POST[$post_id]) === 0 && $field->getValue('usf_mandatory') == 1)
                        || (strlen($_POST[$post_id]) === 0 && $field->getValue('usf_name_intern') === 'EMAIL' && $getNewUser === 2))
                        {
                            $email = $GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_FIELD_EMPTY', $field->getValue('usf_name')));
                            // => EXIT
                        }
                        // Wert aus Feld in das User-Klassenobjekt schreiben
                        $returnCode = $user->setValue($field->getValue('usf_name_intern'), $_POST[$post_id]);

                        // Ausgabe der Fehlermeldung je nach Datentyp
                        if(!$returnCode)
                        {
                                switch ($field->getValue('usf_type'))
                                {
                                        case 'CHECKBOX':
                                                $GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_INVALID_PAGE_VIEW'));
                                                // => EXIT
                                                break;
                                        case 'DATE':
                                                $GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_DATE_INVALID', $field->getValue('usf_name'), $gPreferences['system_date']));
                                                // => EXIT
                                                break;
                                        case 'EMAIL':
                                                $GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_EMAIL_INVALID', $field->getValue('usf_name')));
                                                // => EXIT
                                                break;
                                        case 'NUMBER':
                                        case 'DECIMAL':
                                                $GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('PRO_FIELD_NUMERIC', $field->getValue('usf_name')));
                                                // => EXIT
                                                break;
                                        case 'PHONE':
                                                $GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_PHONE_INVALID_CHAR', $field->getValue('usf_name')));
                                                // => EXIT
                                                break;
                                        case 'URL':
                                                $GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_URL_INVALID_CHAR', $field->getValue('usf_name')));
                                                // => EXIT
                                                break;
                                }
                        }
					}
					else
					{
                        // Checkboxen uebergeben bei 0 keinen Wert, deshalb diesen hier setzen
                        if($field->getValue('usf_type') === 'CHECKBOX')
                        {
                                $user->setValue($field->getValue('usf_name_intern'), '0');
                        }
                        elseif($field->getValue('usf_mandatory') == 1)
                        {
                                $GLOBALS['gMessage']->show($GLOBALS['gL10n']->get('SYS_FIELD_EMPTY', $field->getValue('usf_name')));
                                // => EXIT
                        }
					}
			}
	}

	# add in the state and expiry fields
	$user->setValue( 'L4P_DB_TEMP_PASS_EXPIRATION', \date('Y-m-d', \time() + \cantabnyc\get_configs()->expiry*24*60*60) );
	$user->setValue( 'L4P_DB_TEMP_PASSWORD',        $autogenerated_password ); # keep raw password for the accept email
	$user->setValue( 'L4P_DB_TEMP_PASS_CHANGED',   '2' ); # NB False is 2nd on the list

	/*------------------------------------------------------------*/
	// Save user data to database
	/*------------------------------------------------------------*/
	$GLOBALS['gDb']->startTransaction();
    try {
        $user->saveChangesWithoutRights();

        $savedUser = $user->save();
        $getLastInsertId = $user->getValue('usr_id');
        $applicationType = trim(strtolower($_POST['application_type']));
        $message = trim($_POST['message']);
        $uapp_usr_id = $getLastInsertId;
        if($applicationType == 'member'){
            $applicationSql = " INSERT INTO ".TBL_APPLICATIONS."
                                (uapp_usr_id, application_type, message)
                                VALUES (
                                    $uapp_usr_id,
                                    '$applicationType',
                                    '$message'
                                ) ";
        } else if($applicationType == 'associate') {
            $reference_1 = trim(strtolower($_POST['reference_1']));
            $reference_2 = trim(strtolower($_POST['reference_2']));
            $applicationSql = " INSERT INTO ".TBL_APPLICATIONS."
                        (uapp_usr_id, application_type, reference_1, reference_2, message)
                        VALUES (
                            $uapp_usr_id,
                            '$applicationType',
                            '$reference_1',
                            '$reference_2',
                            '$message'
                        ) ";
        }
        $privateDataSaved = $GLOBALS['gDb']->query($applicationSql);
	} catch(AdmException $e) {
		$e->showHtml();
	}

	$GLOBALS['gDb']->endTransaction();

	// wenn Daten des eingeloggten Users geaendert werden, dann Session-Variablen aktualisieren
	if((int) $user->getValue('usr_id') === (int) $GLOBALS['gCurrentUser']->getValue('usr_id')) {
		$gCurrentUser = $user;
	}

	// unset($_SESSION['profile_request']);
	// $GLOBALS['gNavigation']->deleteLastUrl();

	# show page
	build_page();
}

/**
 * build the page
 */
function build_page () {

	# set headline of the script
	$headline = $GLOBALS['gL10n']->get('L4P_REGISTRATION_RECEIVED');

	$GLOBALS['gNavigation']->addUrl(CURRENT_URL, $headline);

	// create html page object
	$page = new HtmlPage($headline);

    $page->hideMenu();
    $mailToSupport = 'membership@cantabnyc.org';
    $email_field_post_index = 'usf-'. $GLOBALS['gProfileFields']->mProfileFields['EMAIL']->getValue('usf_id');
    $email = $_POST[$email_field_post_index];

	$html = <<<EOD
<!--<p>Thank you for registering. We will contact you shortly</p>-->
<main>
    <div class="layout__container text-center">
        <output class="page">
            <div class="page__header">
                <h3 class="h1 text-center">Almost There</h3>
            </div>
            <div class="alert alert-default text-left">
                <p>
                    The membership commitee is currently reviewing your application.
                </p>
            </div>
            <hr>
            <p class="lead text-center lead-content">
                If <strong>{$email}</strong> is not your email address, <br>
                please <a href="javascript:history.back()">go back</a> and enter correct one.
            </p>
            <div class="alert alert-default text-left">
                <p>
                    If you haven't recieved a decision within 7 days, please <br>
                    contact us at <a href="mailto:{$mailToSupport}">
                    {$mailToSupport}
                    </a>
                </p>
            </div>
        </output>
    </div>
</main>
EOD;

	$page->addHtml( $html );

	$page->addCssFile( "adm_program/modules/registration/asset/css/handle_membership.min.css" );

	$page->show();
}

###
handle_form_post( $organisation_id );
